"use client";
import { useEffect, useRef } from "react";
import { trackClarityEvent } from "../../lib/clarity";
import { EXPEDIA_GENERAL_AFFILIATE_URL } from "../../lib/revenuePartners";
declare global { interface Window { gtag?: (...args: unknown[]) => void; dataLayer?: unknown[]; } }
const rel = "nofollow sponsored noopener noreferrer";
function track(name: string, data: Record<string, string | number>) { const payload = { site: "localdealsflorida.org", ...data }; window.gtag?.("event", name, payload); window.dataLayer?.push({ event: name, ...payload }); trackClarityEvent(name, payload); }
function useView(name: string, type: string) { useEffect(() => track(name, { component_type: type, placement: "conversion_section", page: location.pathname, page_path: location.pathname }), [name, type]); }
export function ConversionScrollAnalytics() { const fired = useRef(new Set<number>()); useEffect(() => { const run = () => { const max = document.documentElement.scrollHeight - innerHeight; const pct = max > 0 ? scrollY / max * 100 : 100; [50, 90].forEach((d) => { if (pct >= d && !fired.current.has(d)) { fired.current.add(d); track(`scroll_${d}`, { scroll_depth: d, page_path: location.pathname }); } }); }; addEventListener("scroll", run, { passive: true }); run(); return () => removeEventListener("scroll", run); }, []); return null; }
export function QuickDealCard() { useView("deal_card_view", "quick_deal"); return <article className="rounded-[24px] border border-[#d8e6e3] bg-white p-6 shadow-lg shadow-[#087f8c]/8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#087f8c]">Popular activity ideas</p><h2 className="mt-2 text-2xl font-black text-[#163235]">Plan The Next Florida Activity</h2><ul className="mt-4 grid gap-2 text-sm font-semibold text-[#52686b]">{["Family attractions", "Free and low-cost activities", "Weekend local plans"].map((x) => <li key={x}>✓ {x}</li>)}</ul><a className="mt-6 inline-flex min-h-12 items-center justify-center rounded-full bg-[#087f8c] px-6 text-sm font-black text-white" href="#local-finds" onClick={() => track("deal_card_click", { component_type: "QuickDealCard", placement: "conversion_section", page: location.pathname, page_path: location.pathname })}>Explore Current Options</a></article>; }
export function RecommendedPartnerCard() { useView("partner_card_view", "recommended_partner"); const click = () => { const p = { component_type: "RecommendedPartnerCard", placement: "conversion_section", page: location.pathname, partner: "expedia", page_path: location.pathname, outbound_url: EXPEDIA_GENERAL_AFFILIATE_URL }; track("partner_card_click", p); track("affiliate_click", p); }; return <article className="rounded-[24px] border border-[#087f8c] bg-[#163235] p-6 text-white shadow-xl shadow-[#087f8c]/15"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#ffb000]">Recommended booking partner</p><h2 className="mt-2 text-2xl font-black">Expedia</h2><p className="mt-3 text-sm font-semibold leading-7 text-white/75">Compare nearby stays and trip options when a local activity becomes a full Florida getaway.</p><a className="mt-6 inline-flex min-h-12 items-center justify-center rounded-full bg-white px-6 text-sm font-black text-[#163235]" href={EXPEDIA_GENERAL_AFFILIATE_URL} target="_blank" rel={rel} onClick={click}>View Current Deals</a><p className="mt-3 text-xs font-bold text-white/60">Affiliate link. We may earn a commission at no extra cost to you.</p></article>; }
